theme: jekyll-theme-cayman
title: InteractIAS: Interactions networks of invasive alien species
description: InteractIAS is a Jupyter notebook to create species interaction networks from the GloBI database with nodes weighted by their area of occupancy
